### ISSUE TITLE
Check script detects two version each time a commit is pushed resulting in a double build

### ISSUE THREAD

**Issue by tremblaysimon** [emerald-squad/concourse-bitbucket-pullrequest-resource#2]
When you create or update a pull-request with a new commit, there is two versions detected by the pull-request Concourse resource. 

In the end there is two builds triggered because of these two versions. Normally it should only detect one version.

Example:
![image](https://user-images.githubusercontent.com/5879940/82620140-c5489980-9ba5-11ea-8c84-c58c7f9cc8de.png)

**Comment by thomasd-** [comment]
This is a side-effect of a change made recently. In order to correct a bug where new commits on older PR got ignored, we had to change the version structure.

So, when a check is made on an existing version history, the last version is repeated with its structure changed, which cause concourse to think there is a new version for the resource.

This behavior will only happen once, when a check with the new resource type is done on a version history made with the ancient resource type. Subsecent checks will behave as expected.
